// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnGSDVvEd-Eq1JmsnoxjsVjGQD1cUUzeg',
    appId: '1:962811506310:web:2846a1c2133638b2aa2b07',
    messagingSenderId: '962811506310',
    projectId: 'invested-19eb7',
    authDomain: 'invested-19eb7.firebaseapp.com',
    storageBucket: 'invested-19eb7.appspot.com',
    measurementId: 'G-B3Z9E5NNYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqTQWF1iAvxQTKYuzd5Dc5BDrP-XMM6do',
    appId: '1:962811506310:android:5e2f468b5f5c0909aa2b07',
    messagingSenderId: '962811506310',
    projectId: 'invested-19eb7',
    storageBucket: 'invested-19eb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuOVw4kCuScZIkZYze5knBy8LW3d6D_XU',
    appId: '1:962811506310:ios:a385ad7a3c730b06aa2b07',
    messagingSenderId: '962811506310',
    projectId: 'invested-19eb7',
    storageBucket: 'invested-19eb7.appspot.com',
    androidClientId: '962811506310-8hbpnc3sateo1uvdag3q1u7e7l7mibnv.apps.googleusercontent.com',
    iosClientId: '962811506310-l3g1atq2l0m813ljcqb9knvr511nrs2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.invested',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuOVw4kCuScZIkZYze5knBy8LW3d6D_XU',
    appId: '1:962811506310:ios:a385ad7a3c730b06aa2b07',
    messagingSenderId: '962811506310',
    projectId: 'invested-19eb7',
    storageBucket: 'invested-19eb7.appspot.com',
    androidClientId: '962811506310-8hbpnc3sateo1uvdag3q1u7e7l7mibnv.apps.googleusercontent.com',
    iosClientId: '962811506310-l3g1atq2l0m813ljcqb9knvr511nrs2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.invested',
  );
}
