server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_IP}:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: lesson-api
          uri: lb://lesson-service
          predicates:
            - Path=/invested_lesson/**
        - id: account-api
          uri: lb://account-service
          predicates:
            - Path=/invested_account/**
        - id: portfolio-api
          uri: lb://portfolio-service
          predicates:
            - Path=/invested_portfolio/**
        - id: order-api
          uri: lb://order-service
          predicates:
            - Path=/invested_order/**
        - id: stock-api
          uri: lb://stock-service
          predicates:
            - Path=/invested_stock/**