server:
  port: 8888

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: lesson-service
          uri: http://lesson-service.invested-registry:8080
          predicates:
            - Path=/invested_lesson/**
        - id: account-service
          uri: http://account-service.invested-registry:8080
          predicates:
            - Path=/invested_account/**
        - id: portfolio-service
          uri: http://portfolio-service.invested-registry:8080
          predicates:
            - Path=/invested_portfolio/**
        - id: order-service
          uri: http://order-service.invested-registry:8080
          predicates:
            - Path=/invested_order/**
        - id: stock-service
          uri: http://stock-service.invested-registry:105
          predicates:
            - Path=/invested_stock/**