server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: stock-api
          uri: lb://stock-api
          predicates:
            - Path=/invested_stock/**