server:
  port: 8888

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: lesson-api
          uri: lb://lesson-api.invested-ecosystem
          predicates:
            - Path=/invested_lesson/**
        - id: account-api
          uri: lb://account-api.invested-ecosystem
          predicates:
            - Path=/invested_account/**
        - id: portfolio-api
          uri: lb://portfolio-api.invested-ecosystem
          predicates:
            - Path=/invested_portfolio/**
        - id: order-api
          uri: lb://order-api.invested-ecosystem
          predicates:
            - Path=/invested_order/**
        - id: stock-api
          uri: lb://stock-api.invested-ecosystem
          predicates:
            - Path=/invested_stock/**