version: "3.9"

services:

 # /////////////////////////////////////////////////////
 # API's

  stock_api:
    build: ./Stock Service
    image: invested-stock-api:1.0
    depends_on:
      - registration_service
    networks:
      - base-net
    deploy:
      replicas: 1

  account_api:
    build: ./Account Service/AccountService
    image: invested-account-api:1.0
    environment:
      - CUSTOM_PASSWORD=${CUSTOM_PASSWORD}
      - CUSTOM_USERNAME=${CUSTOM_USERNAME}
      - DB_HOST=${ACCOUNT_DB_HOST}
      - DB_PASSWORD=${ACCOUNT_DB_PASSWORD}
      - DB_PORT=${ACCOUNT_DB_PORT}
      - DB_USER=${ACCOUNT_DB_USER}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_SECRET=${JWT_SECRET}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - RSA_PRIVATE_KEY=${RSA_PRIVATE_KEY}
      - RSA_PUBLIC_KEY=${RSA_PUBLIC_KEY}
    depends_on:
      - registration_service
    networks:
      - base-net
    deploy:
      replicas: 1

  portfolio_api:
    build: ./Portfolio Service/PortfolioService
    image: invested-portfolio-api:1.0
    environment:
      - DB_USER=${PORTFOLIO_DB_USERNAME}
      - DB_PASSWORD=${PORTFOLIO_DB_PASSWORD}
      - DB_PORT=${PORTFOLIO_DB_PORT}
      - DB_HOST=${PORTFOLIO_DB_HOST}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - registration_service
    networks:
      - base-net 
    deploy:
      replicas: 1

 # ///////////////////////////////////////////////////// 
 # Email Consumers

  confirmation_email_consumer:
    build: ./Email Consumers/ConfirmEmailConsumer
    image: confirm-email-consumer:1.0
    environment:
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_QUEUE=confirmation-email-queue
      - EMAIL_SUBJECT=${CONFIRMATION_EMAIL_SUBJECT}
    depends_on:
      - rabbitmq
    networks:
      - base-net
    deploy:
      replicas: 1

  forgot_pass_email_consumer:
    build: ./Email Consumers/ForgotPassEmailConsumer
    image: forgot-pass-email-consumer:1.0
    environment:
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_QUEUE=forgot-pass-queue
      - EMAIL_SUBJECT=${FORGOT_EMAIL_SUBJECT}
    depends_on:
      - rabbitmq
    networks:
      - base-net
    deploy:
      replicas: 1

  update_email_consumer:
    build: ./Email Consumers/UpdateInfoEmailConsumer
    image: update-info-email-consumer:1.0
    environment:
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_QUEUE=updated-info-queue
      - EMAIL_SUBJECT=${UPDATE_EMAIL_SUBJECT}
    depends_on:
      - rabbitmq
    networks:
      - base-net
    deploy:
      replicas: 1

  order_placed_email_consumer:
    build: ./Email Consumers/OrderPlacedEmailConsumer
    image: order-placed-email-consumer:1.0
    environment:
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_QUEUE=order-placed-email-queue
      - EMAIL_SUBJECT=${ORDER_PLACED_EMAIL_SUBJECT}
    depends_on:
      - rabbitmq
    networks:
      - base-net
    deploy:
      replicas: 1

  order_canceled_email_consumer:
    build: ./Email Consumers/OrderCanceledEmailConsumer
    image: order-canceled-email-consumer:1.0
    environment:
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_QUEUE=order-canceled-email-queue
      - EMAIL_SUBJECT=${ORDER_CANCELED_EMAIL_SUBJECT}
    depends_on:
      - rabbitmq
    networks:
      - base-net
    deploy:
      replicas: 1

  order_fulfilled_email_consumer:
    build: ./Email Consumers/OrderfulfilledConsumer
    image: order-fulfilled-consumer:1.0
    environment:
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_QUEUE=order-fulfilled-email-queue
      - EMAIL_SUBJECT=${ORDER_FULFILLED_EMAIL_SUBJECT}
    depends_on:
      - rabbitmq
    networks:
      - base-net
    deploy:
      replicas: 1

  
  # /////////////////////////////////////////////////////////////
  # Distrubuted System Helpers

  gateway_service:
    build: "./Gateway"
    image: "invested-gateway:1.0"
    depends_on:
      - stock_api
    ports:
      - "8888:8888"
    networks:
      - base-net

  registration_service:
    image: "steeltoeoss/eureka-server"
    container_name: "eureka"
    ports:
      - "8761:8761"
    networks:
    - base-net

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - base-net

  # /////////////////////////////////////////////////////////////
  # Databases

  forgot_pass_code_database:
    image: "redis:alpine"
    container_name: verify-code-database
    ports:
      - "6379:6379"
    networks:
      - base-net

  account_database:
    image: "mysql:latest"
    container_name: invested-account-db
    environment:
      - MYSQL_DATABASE=accounts 
      - MYSQL_USER=${ACCOUNT_MYSQL_USER}
      - MYSQL_PASSWORD=${ACCOUNT_MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${ACCOUNT_MYSQL_PASSWORD}
    ports:
      - "9000:3306"
    networks:
      - base-net

  order_database:
    image: "mysql:latest"
    container_name: invested-orders-db
    environment:
      - MYSQL_DATABASE=orders
      - MYSQL_USER=${ORDER_MYSQL_USER}
      - MYSQL_PASSWORD=${ORDER_MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${ORDER_MYSQL_PASSWORD}
    ports:
      - "9001:3306"
    networks:
      - base-net

  portfolio_database:
    image: "mysql:latest"
    container_name: invested-portfolios-db
    environment:
      - MYSQL_DATABASE=portfolios
      - MYSQL_USER=${PORTFOLIO_MYSQL_USER}
      - MYSQL_PASSWORD=${PORTFOLIO_MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PORTFOLIO_MYSQL_PASSWORD}
    ports:
      - "9002:3306"
    networks:
      - base-net

networks:
  base-net:
    name: "invested_ecosystem"